document.addEventListener('DOMContentLoaded',()=>{
const whatsapp='201112736689',email='clothinghubegypt4@gmail.com';
const mobileMenu=document.getElementById('mobileMenu'),mobileNav=document.getElementById('mobileNav');mobileMenu?.addEventListener('click',()=>mobileNav?.classList.toggle('open'));mobileNav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>mobileNav.classList.remove('open')));
const searchBtn=document.getElementById('searchBtn'),searchbar=document.getElementById('searchbar'),searchInput=document.getElementById('searchInput');searchBtn?.addEventListener('click',()=>{searchbar?.classList.toggle('open');if(searchbar?.classList.contains('open'))searchInput?.focus()});
const products=[...document.querySelectorAll('.product')],filters=[...document.querySelectorAll('.filter')];
function refresh(){const term=(searchInput?.value||'').trim().toLowerCase(),active=document.querySelector('.filter.active')?.dataset.filter||'all';products.forEach(card=>{const cat=(card.dataset.category||'').toLowerCase(),text=card.textContent.toLowerCase();card.style.display=(active==='all'||cat===active)&&(!term||text.includes(term))?'':'none'})}
filters.forEach(b=>b.addEventListener('click',()=>{filters.forEach(x=>x.classList.remove('active'));b.classList.add('active');refresh()}));searchInput?.addEventListener('input',refresh);
document.querySelectorAll('.quick').forEach(button=>button.addEventListener('click',()=>{const product=button.dataset.product||'product';window.open(`https://wa.me/${whatsapp}?text=${encodeURIComponent(`Hello Clothing Hub Egypt, I am interested in ${product}. Please send me the current wholesale price, MOQ, available options and shipping details.`)}`,'_blank','noopener,noreferrer')}));
const form=document.getElementById('inquiryForm');form?.addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(form).entries());const msg=`Hello Clothing Hub Egypt, I would like a wholesale quotation.\n\nName: ${d.name||''}\nCompany: ${d.company||''}\nEmail: ${d.email||''}\nCountry: ${d.country||''}\nProduct: ${d.product||''}\nQuantity: ${d.quantity||''}\nRequirements: ${d.message||''}`;window.open(`https://wa.me/${whatsapp}?text=${encodeURIComponent(msg)}`,'_blank','noopener,noreferrer');form.reset()});
document.querySelectorAll('a[href^="mailto:"]').forEach(a=>a.href=`mailto:${email}`);document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href'),t=id&&document.querySelector(id);if(t){e.preventDefault();t.scrollIntoView({behavior:'smooth',block:'start'})}}));refresh();
});